#ifndef __ABOUT_H__
#define __ABOUT_H__

//---------------------------------------------------------------------------
//
//	File:			ABOUT.H
//	Programmer: 	Bob Provencher
//	Create Date:	11/6/94
//	Last Mod Date:	1/2/95
//	Description:	About dialog box header file
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------

#ifndef __PRECOMP_H__
#include "precomp.h"
#endif

BOOL CALLBACK _export About( HWND hDlg, UINT message, 
							 WPARAM wParam, LPARAM lParam );

#endif
