#ifndef __CLASSDEF_H__
#define __CLASSDEF_H__

//---------------------------------------------------------------------------
//
//	File:			CLASSDEF.H
//	Programmer: 	Bob Provencher
//	Create Date:	11/9/94
//	Last Mod Date:	1/2/95
//	Description:	class forward references
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------

#ifndef __PRECOMP_H__
#include "precomp.h"
#endif

class WinGDC;
class WinGBitmap;
class LogPalette;
class Palette;
class BitmapInfo;
class DIBitmap;

class Map;

#endif



