//---------------------------------------------------------------------------
//
//	File:			GEN.CPP
//	Programmer: 	Bob Provencher
//	Create Date:	11/27/94
//	Last Mod Date:	1/8/95
//	Description:    general purpose functions
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------

#include "precomp.h"
#pragma hdrstop

#include "gen.h"

