#ifndef __PRECOMP_H__
#define __PRECOMP_H__

//---------------------------------------------------------------------------
//
//	File:			PRECOMP.H
//	Programmer: 	Bob Provencher
//	Create Date:	11/6/94
//	Last Mod Date:	1/2/95
//	Description:	Precompiled headers for WinG: From the Top Down
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------

#include <windows.h>
#include <windowsx.h>
#include <mmsystem.h>
#include <wing.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <mem.h>
#include <limits.h>

#endif


