//--------------------------------------------------------------------------
//
//	File:			RES.CPP
//	Programmer:		Bob Provencher
//	Create Date:	12/1/94
//	Last Mod Date:	1/2/95
//	Description:	Resource load class
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//--------------------------------------------------------------------------

#include "precomp.h"
#pragma hdrstop

#include "res.h"

HINSTANCE Resource::hInst = (HINSTANCE)SELECTOROF( &hInst );






