#ifndef __TILES_H__
#define __TILES_H__

//---------------------------------------------------------------------------
//
//	File:	        TILE.H
//	Programmer:     Bob Provencher
//	Create Date:    12/16/94
//	Last Mod Date:  1/1/95
//	Description:    Tile defines
//
//	Copyright (c) 1994, 1995. Aesir Software, Inc.
//	All Rights Reserved.
//
//---------------------------------------------------------------------------

#define TILE_FLOOR		0
#define TILE_PLAYER		1
#define TILE_WALL		2
#define TILE_GOLD		3
#define TILE_MONSTER	4

#endif


